import type { Metadata } from 'next'
import './globals.css'
import { Header, Footer } from '@/components'

export const metadata: Metadata = {
  title: 'Nike App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        <main className='relative'>
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  )
}
